# Generated by Django 4.0 on 2022-01-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_ticket_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='titre',
            new_name='title',
        ),
        migrations.AddField(
            model_name='userfollows',
            name='follows',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
